export { default as Blank } from './Blank'
export { default as CookiePolicy } from './CookiePolicy'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export { default as QiblaCompass } from './QiblaCompass'
export { default as TermsOfUse } from './TermsOfUse'
