export * from './QiblaCompass'
export { default as KibleYonTayini } from './q1'
export { default as QiblaFinder } from './q2'
export { default as CookiePolicy } from './CookiePolicy'
export { default as PrivacyPolicy } from './PrivacyPolicy'
export { default as TermsOfUse } from './TermsOfUse'